name: 'Run Tests'
description: 'Validate Debian packaging files'

runs:
  using: 'composite'
  steps:
    - name: Validate debian packaging files
      shell: bash
      run: |
        # Check that essential files exist
        test -f VERSION || (echo "ERROR: VERSION file missing" && exit 1)
        test -f debian/control || (echo "ERROR: debian/control missing" && exit 1)
        test -f debian/rules || (echo "ERROR: debian/rules missing" && exit 1)

        # Validate VERSION file format (accepts 3 or 4 part versions)
        VERSION=$(cat VERSION | tr -d '[:space:]')
        if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?$'; then
          echo "ERROR: VERSION file must contain semantic version (e.g., 1.0.7 or 1.0.7.2)"
          exit 1
        fi

        echo "Validation passed"
        echo "VERSION: $VERSION"
